version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ROOM_EXPIRATION_TIME: 3600
      PORT: 3000

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
